import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Officelite Coming Soon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header></header>
        <div>
          <h1>A simple solution to complex tasks is coming soon</h1>

          <p>
            Say goodbye to inefficient juggling of multiple apps, teams, and
            projects. Officelite is the new collaboration platform built with an
            intuitive interface to improve productivity.
          </p>

          <div>Get Started</div>
        </div>
        <div>
          <div>
            <h3>Basic</h3>
            <h2>Free</h2>
            <p>Up to 5 users for free</p>
            <ul>
              <li>Basic document collaboration</li>
              <li>2 gb storage</li>
              <li>Great security and support</li>
            </ul>
            <div>Try for Free</div>
          </div>

          <div>
            <h3>Pro</h3>
            <h2>$9.99</h2>
            <p>Per user, billed monthly</p>
            <ul>
              <li>All essential integrations</li>
              <li>50 gb storage</li>
              <li>More control and insights</li>
            </ul>
            <div>Try for Free</div>
          </div>

          <div>
            <h3>Ultimate</h3>
            <h2>$19.99</h2>
            <ul>
              <li>Per user, billed monthly</li>
              <li>Robust work management</li>
              <li>100 gb storage</li>
              <li>VIP support</li>
            </ul>
            <div>Try for Free</div>
          </div>
        </div>

        <div>
          {/*If you're choosing to make this date dynamic, set it to 30 days in the future from the moment the visitor views the page */}
          <p>Coming 4 Nov 2021</p>
          <div>
            {/* If you're choosing to make this timer dynamic, have it countdown from the date you set above */}
            <div>47 Days</div>
            <div>07 Hours</div>
            <div>56 Min</div>
            <div>14 Sec</div>
            <div>
              <div>Get Started</div>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
