import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Officelite Coming Soon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Image
          priority
          className={styles.header__Image1}
          src="/assets/shared/logo.svg"
          alt="logo"
          width={155}
          height={30}
        />
      </header>
      <main>
        <section className={styles.home}>
          <div className={styles.header__Image2}>
            <Image
              priority
              src="/assets/home/bg-pattern-header.svg"
              height={458}
              width={458}
              alt="bg-pattern"
            />
          </div>

          <div className={styles.intro}>
            <div className={styles.intro__image}>
              <Image
                priority
                src="/assets/home/illustration-charts.svg"
                width={171}
                height={192}
                alt="charts"
              />
            </div>
            <h1 className={styles.home__1}>
              A simple solution to complex tasks is coming soon
            </h1>

            <p>
              Say goodbye to inefficient juggling of multiple apps, teams, and
              projects. Officelite is the new collaboration platform built with
              an intuitive interface to improve productivity.
            </p>

            <div className={styles.button}>Get Started</div>
          </div>
        </section>

        <section className={styles.card}>
          <div className={styles.card__basic}>
            <h3>Basic</h3>
            <h1>Free</h1>
            <p>Up to 5 users for free</p>
            <ul>
              <li>Basic document collaboration</li>
              <li>2 gb storage</li>
              <li>Great security and support</li>
            </ul>
            <div className={styles.button}>Try for Free</div>
          </div>

          <div>
            <h3>Pro</h3>
            <h2>$9.99</h2>
            <p>Per user, billed monthly</p>
            <ul>
              <li>All essential integrations</li>
              <li>50 gb storage</li>
              <li>More control and insights</li>
            </ul>
            <div>Try for Free</div>
          </div>

          <div>
            <h3>Ultimate</h3>
            <h2>$19.99</h2>
            <ul>
              <li>Per user, billed monthly</li>
              <li>Robust work management</li>
              <li>100 gb storage</li>
              <li>VIP support</li>
            </ul>
            <div>Try for Free</div>
          </div>
        </section>

        <div>
          {/*If you're choosing to make this date dynamic, set it to 30 days in the future from the moment the visitor views the page */}
          <p>Coming 4 Nov 2021</p>
          <div>
            {/* If you're choosing to make this timer dynamic, have it countdown from the date you set above */}
            <div>47 Days</div>
            <div>07 Hours</div>
            <div>56 Min</div>
            <div>14 Sec</div>
            <div>
              <div>Get Started</div>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
